# Generated by Django 2.0.6 on 2018-06-18 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Userdata'),
        ),
    ]
